/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_mapout_jni_JNILoader */

#ifndef _Included_net_mapout_jni_JNILoader
#define _Included_net_mapout_jni_JNILoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_mapout_jni_JNILoader
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_mapout_jni_JNILoader_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
